import { Inter } from "@next/font/google";
import { NextPage } from "next";
import Head from "next/head";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <p className="text-blue-300">ttt</p>
      </div>
    </>
  );
};

export default Home;
